numeric_vector <- c(1, 2.5, 3.7, 4, 5.2)
character_vector <- c("apple", "banana", "cherry", "date")
logical_vector <- c(TRUE, FALSE, TRUE, TRUE, FALSE)
cat("Numeric Vector:\n")
print(numeric_vector)
cat("\nCharacter Vector:\n")
print(character_vector)
cat("\nLogical Vector:\n")
print(logical_vector)
cat("\nType of Numeric Vector:\n")
print(typeof(numeric_vector))
cat("\nType of Character Vector:\n")
print(typeof(character_vector))
cat("\nType of Logical Vector:\n")
print(typeof(logical_vector))

